name: build 6 single volume PDFs
on:
  workflow_dispatch:
  
jobs:
  hpmor-1:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
      with:
        ref: main
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token

#    - name: setup environment to DE lang
#      run: |
#        cd /usr/share/locales
#        sudo ./install-language-pack de_DE.UTF-8   

    - name: install requirements
      run: sh scripts/install_requirements_pdf.sh > /dev/null

    - name: latexmk
      run: latexmk hpmor-1 > /dev/null

    - name: publish PDF to release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: WorkInProgress
        prerelease: true
        files: hpmor-1.pdf

  hpmor-2:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
      with:
        ref: main
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token

#    - name: setup environment to DE lang
#      run: |
#        cd /usr/share/locales
#        sudo ./install-language-pack de_DE.UTF-8   

    - name: install requirements
      run: sh scripts/install_requirements_pdf.sh > /dev/null

    - name: latexmk
      run: latexmk hpmor-2 > /dev/null

    - name: publish PDF to release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: WorkInProgress
        prerelease: true
        files: hpmor-2.pdf

  hpmor-3:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
      with:
        ref: main
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token

 #   - name: setup environment to DE lang
 #     run: |
 #       cd /usr/share/locales
 #       sudo ./install-language-pack de_DE.UTF-8   

    - name: install requirements
      run: sh scripts/install_requirements_pdf.sh > /dev/null

    - name: latexmk
      run: latexmk hpmor-3 > /dev/null

    - name: publish PDF to release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: WorkInProgress
        prerelease: true
        files: hpmor-3.pdf

  hpmor-4:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
      with:
        ref: main
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token

#    - name: setup environment to DE lang
#      run: |
#        cd /usr/share/locales
#        sudo ./install-language-pack de_DE.UTF-8   

    - name: install requirements
      run: sh scripts/install_requirements_pdf.sh > /dev/null

    - name: latexmk
      run: latexmk hpmor-4 > /dev/null

    - name: publish PDF to release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: WorkInProgress
        prerelease: true
        files: hpmor-4.pdf

  hpmor-5:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
      with:
        ref: main
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token

 #   - name: setup environment to DE lang
 #     run: |
 #       cd /usr/share/locales
 #       sudo ./install-language-pack de_DE.UTF-8   

    - name: install requirements
      run: sh scripts/install_requirements_pdf.sh > /dev/null

    - name: latexmk
      run: latexmk hpmor-5 > /dev/null

    - name: publish PDF to release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: WorkInProgress
        prerelease: true
        files: hpmor-5.pdf

  hpmor-6:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
      with:
        ref: main
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token

#    - name: setup environment to DE lang
#      run: |
#        cd /usr/share/locales
#        sudo ./install-language-pack de_DE.UTF-8   

    - name: install requirements
      run: sh scripts/install_requirements_pdf.sh > /dev/null

    - name: latexmk
      run: latexmk hpmor-6 > /dev/null

    - name: publish PDF to release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: WorkInProgress
        prerelease: true
        files: hpmor-6.pdf
